services:

  mysql-server:
    image: mysql:8.4
    container_name: mysql-db
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5

  php-apache-server:
    build:
      context: .
      dockerfile: Dockerfile.php
    container_name: php-apache
    volumes:
      - ./www:/var/www/html
      - ./apache-config/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
    ports:
      - "80:80"
    depends_on:
      mysql-server:
        condition: service_healthy

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin
    ports:
      - "8082:80"
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: root
    depends_on:
      mysql-server:
        condition: service_healthy

volumes:
  mysql_data: